### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by IvanVakhrameyeu** [vachrameev/4tune#1]
- **Сайт** 
- [x]  Аунтификация
- [ ]  Вход через vk

- Игры
- [ ] Сделать Double game
- [ ] Сделать jackpot game
- [ ] Сделать nvuti game

-  **Модерирование**
- [ ]  Возможность удаление сообщение
- [ ]  Возможность банить пользователей на какое то время

**Comment by vachrameev** [comment]
> * **Сайт**
> * [x]   Аунтификация
> * [ ]   Регистрация
> * [ ]   Восстановление пароля
> * [x]   Вход через GitHub
> * [x]   Вход через vk
> * [x]   Вход через odnoklasniki
> * [x]   Вход через facebook
> * [x]   Вход через twitter
> * [x]   Вход через google
> * **Модерирование**
> * [ ]   Возможность удаление сообщение
> * [ ]   Возможность банить пользователей на какое то время
